version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    depends_on:
      - sqlserver
      - redis
      - rabbitmq
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings_Redis="redis:6379"
        - ConnectionStrings_RabitMQ="rabbitmq:5672"
    networks:
        - notifymenetwork
    restart: on-failure 
  sqlserver:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        SA_PASSWORD: ${SA_PASSWORD}
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sql_data:/data
    networks:
        - notifymenetwork
  redis:
    image: redis:latest  
    container_name: redis-cache
    ports:
        - "6379:6379"
    volumes:
        - redis_data:/data  
    networks:
        - notifymenetwork
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
        - notifymenetwork
networks:
  notifymenetwork:
volumes:
  sql_data:
  redis_data: